
name: Patch Desugared Jar on Jar Commit

on:
  push:
    branches:
      - main
    paths:
      - 'classes_java7.jar'
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Debug - list root files
        run: ls -lh

      - name: Unpack committed desugared jar
        run: |
          mkdir -p build/unpacked
          unzip -o classes_java7.jar -d build/unpacked
    
      - name: Compile PatchLoadLibRemover
        run: |
          mkdir -p build/tools
          javac -cp asm-9.4.jar:asm-commons-9.4.jar tools/PatchLoadLibRemover.java -d build/tools
    
      - name: Run PatchLoadLibRemover on OnnxRuntime.class
        run: java -cp build/tools:asm-9.4.jar:asm-commons-9.4.jar tools.PatchLoadLibRemover build/unpacked/ai/onnxruntime/OnnxRuntime.class

      - name: Repack patched jar
        run: |
          cd build/unpacked
          jar cf ../classes_java7_patched.jar .
          cd ../..

      - name: Upload patched jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7-patched
          path: build/classes_java7_patched.jar
