name: Desugar using d8.dex

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check d8.dex and classes.jar presence
        run: |
          ls -lh d8.dex
          ls -lh classes.jar

      - name: Create output directory
        run: mkdir -p build

      - name: Run d8.dex using dalvikvm
        run: |
          dalvikvm -cp d8.dex com.android.tools.r8.D8 --release 7 --output build classes.jar

      - name: Verify output
        run: ls -lh build

      - name: Upload desugared output
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build
