name: Desugar to Java 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Compile Java sources targeting Java 8 bytecode
        run: |
          mkdir -p build/classes
          find src -name "*.java" > sources.txt || true
          if [ -s sources.txt ]; then
            javac -source 8 -target 8 -d build/classes @sources.txt
            jar cf build/classes.jar -C build/classes .
          else
            echo "No Java source files found in src/. Skipping compile step."
            exit 1
          fi

      - name: Check desugar.jar presence
        run: ls -lh desugar-1.0.1.jar

      - name: Run Desugar on compiled classes.jar
        run: |
          mkdir -p build
          BOOTCLASSPATH=$JAVA_HOME/jre/lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Error: rt.jar not found at $BOOTCLASSPATH"
            exit 1
          fi

          java -cp desugar-1.0.1.jar com.google.devtools.build.android.desugar.Desugar \
            --input build/classes.jar \
            --output build/classes_java7.jar \
            --classpath_entry "" \
            --bootclasspath_entry "$BOOTCLASSPATH"

      - name: Upload Java 7 jar
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
