name: Desugar to Java 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check desugar.jar and classes.jar presence
        run: |
          ls -lh tools/desugar.jar
          ls -lh classes.jar

      - name: Run Desugar on existing classes.jar
        run: |
          BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "rt.jar not found at $BOOTCLASSPATH, trying alternative path"
            BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../jre/lib/rt.jar
          fi
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Warning: rt.jar not found, Desugar might fail"
          fi

          java -cp tools/desugar.jar com.google.devtools.build.android.desugar.Desugar \
            --input classes.jar \
            --output build/classes_java7.jar \
            --classpath_entry "" \
            --bootclasspath_entry "$BOOTCLASSPATH"

      - name: Upload desugared jar
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
