name: Desugar to Java 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Bazel
      uses: bazelbuild/setup-bazel@v3
      with:
        bazel-version: 6.5.0

    - name: Clone Desugar sources
      run: |
        git clone https://android.googlesource.com/tools/base
        cd base
        git checkout studio-2024.1.1.21
        cd ..

    - name: Build Desugar jar
      run: |
        cd base
        bazel build //:desugar_deploy.jar
        cd ..
        mkdir tools
        cp base/bazel-bin/desugar_deploy.jar tools/desugar.jar

    - name: Compile your Java sources
      run: |
        mkdir -p build
        javac -source 8 -target 8 -d build $(find src -name "*.java")
        jar cf build/classes.jar -C build .

    - name: Run Desugar
      run: |
        java -cp tools/desugar.jar com.google.devtools.build.android.desugar.Desugar \
          --input build/classes.jar \
          --output build/classes_java7.jar \
          --classpath_entry "" \
          --bootclasspath_entry $(dirname $(readlink -f $(which javac)))/../lib/rt.jar

    - name: Upload Java 7 jar
      uses: actions/upload-artifact@v4
      with:
        name: classes-java7
        path: build/classes_java7.jar
