name: Desugar to Java 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: 8

      - name: Check required files
        run: |
          ls -lh classes.jar
          ls -lh desugar-1.0.1.jar

      - name: Prepare directories
        run: |
          mkdir -p build
          mkdir -p $GITHUB_WORKSPACE/lambda_dump

      - name: Run Desugar on classes.jar
        run: |
          BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "rt.jar not found at $BOOTCLASSPATH, trying alternative path"
            BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../jre/lib/rt.jar
          fi
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Warning: rt.jar not found, Desugar might fail"
          fi

          java -cp desugar-1.0.1.jar com.google.devtools.build.android.desugar.Desugar \
            --input classes.jar \
            --output build/classes_java7.jar \
            --lambda_dump_dir $GITHUB_WORKSPACE/lambda_dump \
            --bootclasspath_entry "$BOOTCLASSPATH" \
            --release 7 \
            --allow-empty

      - name: Upload desugared jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
