name: Desugar to Java 7 (via d8 downgrade)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Check presence of required files
        run: |
          ls -lh desugar-1.0.1.jar
          ls -lh classes.jar

      - name: Create build directories
        run: |
          mkdir -p build/classes_d8

      - name: Run d8 to downgrade classes.jar to Java 8 bytecode
        run: |
          java -cp desugar-1.0.1.jar com.android.tools.r8.D8 \
            --release 8 \
            --output build/classes_d8 \
            classes.jar

      - name: Create jar from d8 output
        run: |
          cd build/classes_d8
          jar cf ../classes_d8.jar .
          cd ../../

      - name: Run Desugar on downgraded classes jar
        run: |
          mkdir -p build
          BOOTCLASSPATH=$JAVA_HOME/jre/lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Error: rt.jar not found at $BOOTCLASSPATH"
            exit 1
          fi

          java -cp desugar-1.0.1.jar com.google.devtools.build.android.desugar.Desugar \
            --input build/classes_d8.jar \
            --output build/classes_java7.jar \
            --classpath_entry "" \
            --bootclasspath_entry "$BOOTCLASSPATH"

      - name: Upload Java 7 jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
