name: Desugar to Java 7 with D8

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check classes.jar presence
        run: ls -lh classes.jar

      - name: Setup Android SDK Commandline tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d cmdline-tools
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=${PWD}/android-sdk "build-tools;33.0.2"

      - name: Run D8 to convert classes.jar to Java 8 compatible bytecode
        run: |
          mkdir -p build/classes_d8
          ./android-sdk/build-tools/33.0.2/d8 --release --output build/classes_d8 classes.jar
    
      - name: Upload D8 output
        uses: actions/upload-artifact@v4
        with:
          name: classes_d8
          path: build/classes_d8
