name: Desugar to Java 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check presence of jars
        run: |
          ls -lh desugar-1.0.1.jar
          ls -lh classes.jar

      - name: Prepare directories
        run: |
          mkdir -p build
          mkdir -p /tmp/lambdas

      - name: Run Desugar on classes.jar
        run: |
          BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "rt.jar not found at $BOOTCLASSPATH, trying alternative path"
            BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../jre/lib/rt.jar
          fi
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Warning: rt.jar not found, Desugar might fail"
          fi

          java --add-opens java.base/java.lang.invoke=ALL-UNNAMED \
            -cp desugar-1.0.1.jar com.google.devtools.build.android.desugar.Desugar \
            --input classes.jar \
            --output build/classes_java7.jar \
            --lambda_dump_dir /tmp/lambdas \
            --bootclasspath_entry "$BOOTCLASSPATH" || true  # don't fail on warning

      - name: Upload desugared jar
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
