name: Desugar to Java 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download prebuilt desugar jar
        run: |
          wget https://storage.googleapis.com/android-build-tools/desugar/desugar.jar -O tools/desugar.jar
        # Create tools dir if missing
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          TOOLSDIR: tools
        # Create tools folder if not exists
      - name: Ensure tools directory exists
        run: mkdir -p tools

      - name: Compile your Java sources
        run: |
          mkdir -p build/classes
          find src -name "*.java" > sources.txt
          javac -source 8 -target 8 -d build/classes @sources.txt
          jar cf build/classes.jar -C build/classes .

      - name: Run Desugar
        run: |
          BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "rt.jar not found at $BOOTCLASSPATH, trying alternative path"
            BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../jre/lib/rt.jar
          fi
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Error: rt.jar not found, Desugar might fail"
            exit 1
          fi
          java -cp tools/desugar.jar com.google.devtools.build.android.desugar.Desugar \
            --input build/classes.jar \
            --output build/classes_java7.jar \
            --classpath_entry "" \
            --bootclasspath_entry "$BOOTCLASSPATH"

      - name: Upload Java 7 jar
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
