name: Extract desugar.jar from AAR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  extract_desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download android_build_tools.aar
        run: |
          wget -O android_build_tools.aar "https://example.com/path/to/android_build_tools.aar"

      - name: Create tools directory
        run: mkdir -p tools

      - name: Extract desugar.jar from AAR
        run: |
          unzip -j android_build_tools.aar classes.jar -d tools
          unzip -j android_build_tools.aar desugar.jar -d tools
          ls -l tools

      - name: Compile your Java sources
        run: |
          mkdir -p build/classes
          find src -name "*.java" > sources.txt
          javac -source 8 -target 8 -d build/classes @sources.txt
          jar cf build/classes.jar -C build/classes .

      - name: Run Desugar
        run: |
          BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "rt.jar not found at $BOOTCLASSPATH, trying alternative path"
            BOOTCLASSPATH=$(dirname $(readlink -f $(which javac)))/../jre/lib/rt.jar
          fi
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Error: rt.jar not found, Desugar might fail"
            exit 1
          fi
          java -cp tools/desugar.jar com.google.devtools.build.android.desugar.Desugar \
            --input build/classes.jar \
            --output build/classes_java7.jar \
            --classpath_entry "" \
            --bootclasspath_entry "$BOOTCLASSPATH"

      - name: Upload Java 7 jar
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
