name: Desugar to Java 7

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install OpenJDK 8
        run: sudo apt-get update && sudo apt-get install -y openjdk-8-jdk

      - name: Check desugar.jar and classes.jar presence
        run: |
          ls -lh desugar-1.0.1.jar
          ls -lh classes.jar

      - name: Run Desugar on existing classes.jar
        run: |
          mkdir -p build
          BOOTCLASSPATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
          if [ ! -f "$BOOTCLASSPATH" ]; then
            echo "Error: rt.jar not found at $BOOTCLASSPATH"
            exit 1
          fi

          java -cp desugar-1.0.1.jar com.google.devtools.build.android.desugar.Desugar \
            --input classes.jar \
            --output build/classes_java7.jar \
            --classpath_entry "" \
            --bootclasspath_entry "$BOOTCLASSPATH"

      - name: Upload Java 7 jar
        uses: actions/upload-artifact@v4
        with:
          name: classes-java7
          path: build/classes_java7.jar
