name: Convert ONNX to TFLite

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model.onnx from Release asset
        run: |
          echo "Downloading from fixed URL"
          curl -L -o model.onnx "https://github.com/DanexCodr/Exhhdbd/releases/download/Durhrj/model.onnx"
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install tensorflow==2.13.0 tensorflow-probability==0.19.0 tensorflow-addons==0.20.0 onnx onnx-tf
    
      - name: Run conversion script
        run: |
          python convert.py

      - name: Upload TFLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-tflite
          path: model.tflite
