name: Convert ONNX to TFLite

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model.onnx from Release asset
        run: |
          echo "Downloading from fixed URL"
          curl -L -o model.onnx "https://github.com/DanexCodr/Exhhdbd/releases/download/Durhrj/model.onnx"

      - name: Verify downloaded ONNX file
        run: |
          ls -lh model.onnx
          head -20 model.onnx || echo "File head not readable"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --force-reinstall tensorflow==2.12.0 tensorflow-probability==0.19.0 onnx==1.14.0 onnx-tf==1.10.0 onnx-simplifier

      - name: Simplify ONNX model
        run: |
          python -m onnxsim model.onnx model_simplified.onnx

      - name: Echo ONNX model inspection commands
        run: |
          echo "import onnx"
          echo "model = onnx.load('model_simplified.onnx')"
          echo "for node in model.graph.node:"
          echo "    for attr in node.attribute:"
          echo "        if attr is None:"
          echo "            print('Node with None attribute:', node)"

      - name: Run conversion script
        run: |
          python convert.py model_simplified.onnx model.tflite

      - name: Verify TFLite output presence
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la
          if [ ! -f model.tflite ]; then
            echo "Error: model.tflite not found!"
            exit 1
          else
            echo "model.tflite found! Size:"
            ls -lh model.tflite
          fi

      - name: Upload TFLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-tflite
          path: model.tflite
