name: Convert ONNX to TFLite

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model.onnx from Release asset
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/DanexCodr/Exhhdbd/releases/tags/Durhrj \
            | grep browser_download_url \
            | grep model.onnx \
            | cut -d '"' -f 4)
          echo "Downloading from $DOWNLOAD_URL"
          curl -L -o model.onnx "$DOWNLOAD_URL"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install onnx onnx-tf tensorflow

      - name: Run conversion script
        run: |
          python convert.py

      - name: Upload TFLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-tflite
          path: model.tflite
