name: Quantize ONNX Model with quantisize.py

on:
  push:
    branches:
      - main

jobs:
  quantize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download model.onnx from Release asset
        run: |
          curl -L -o model.onnx "https://github.com/DanexCodr/Exhhdbd/releases/download/Durhrj/model.onnx"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install onnx onnxruntime onnxruntime-tools

      - name: Run quantisize.py script
        run: |
          python quantize.py model.onnx model_quant.onnx

      - name: Verify quantized model
        run: ls -lh model_quant.onnx

      - name: Upload quantized model
        uses: actions/upload-artifact@v4
        with:
          name: quantized-model
          path: model_quant.onnx
