name: Desugar classes.jar

on:
  push:
    branches:
      - main

jobs:
  desugar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Bazel manually
        run: |
          sudo apt update
          sudo apt install -y curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install -y bazel-6.5.0
          bazel version

      - name: Download desugar.jar
        run: |
          wget https://repo1.maven.org/maven2/com/google/devtools/build/desugar/desugar/1.1.5/desugar-1.1.5.jar -O desugar.jar

      - name: Run desugar on classes.jar
        run: |
          java -jar desugar.jar --input classes.jar --output classes-desugared.jar --min-sdk-version 21

      - name: Check output
        run: |
          ls -lh classes-desugared.jar
